openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
tags:
  - name: User
    description: Операции с пользователями
  - name: Product
    description: Операции с продуктами

paths:
#  /users/{user_id}:
#    get:
#      description: Get user
#      operationId: GetUser
#      tags:
#        - User
#      parameters:
#        - name: user_id
#          in: path
#          required: true
#          schema:
#            type: string
#            format: uuid
#      responses:
#        200:
#          description: Return user
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: "#/components/schemas/User"
  /servers/available:
    get:
      operationId: GetAvailableServers
      responses:
        200:
          description: Return servers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Server"
  /rent/{server_id}:
    post:
      operationId: RentServer
      parameters:
        - name: server_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Return user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Server"


components:
  schemas:
    Server:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        cpu:
          format: int
          description: core
        memory:
          format: int
          description: MB
        disk:
          format: int
          description: MB
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string